#!/bin/sh
# Back up data saved on node and 

ADDR=$1

VIDDIR=$SAVEDIR/$ADDR/Videos
LOGDIR=$SAVEDIR/$ADDR/log

if [ ! -d "$LOGDIR" ];
then
    echo "Creating log backup dir: $LOGDIR"
    mkdir -p $LOGDIR || echo "Failed to create $LOGDIR"
fi

rsync -a pi@$ADDR:/var/log/syslog $LOGDIR &> /dev/null  || echo "ERROR: Log sync failed: $ADDR"

if [ ! -d "$VIDDIR" ];
then
    echo "Creating video backup dir: $VIDDIR"
    mkdir -p $VIDDIR || echo "Failed to create $VIDDIR"
fi

rsync -a pi@$ADDR:Videos/ $VIDDIR &> /dev/null || echo "ERROR: Video sync failed: $ADDR"


exit 0
