#!/bin/sh
# Back up data saved on node and 

ADDR=$1

logger "Backing up node: $ADDR";

VIDDIR=~/$ADDR/Videos
LOGDIR=~/$ADDR/log

if [ ! -d "$LOGDIR" ];
then
    logger "Creating log backup dir: $LOGDIR"
    mkdir -p $LOGDIR || logger "Failed to create $LOGDIR"
fi

rsync -a pi@$ADDR:/var/log/syslog $LOGDIR  || logger "Log sync failed: $ADDR"

if [ ! -d "$VIDDIR" ];
then
    logger "Creating video backup dir: $VIDDIR"
    mkdir -p $VIDDIR || logger "Failed to create $VIDDIR"
fi


rsync -a pi@$ADDR:Videos/ $VIDDIR || logger "Video sync failed: $ADDR"


exit
