#!/bin/bash


ID=0525:a4a2

logger "Searching for $ID"
devPath=`lsusb | grep $ID | sed -r 's/Bus ([0-9]{3}) Device ([0-9]{3}).*/bus\/usb\/\1\/\2/g;'`
logger "Found $ID @ $devPath"
logger "Searching for sysPath"
for sysPath in /sys/bus/usb/devices/*; do
    logger "$sysPath/uevent"
    devName=`cat "$sysPath/uevent" | grep $devPath`
    #logger devName=$devName
    if [ ! -z $devName ] 
    then
        break
    fi
done
if [ ! -z  $devName ] 
then
    logger "Found $ID @ $sysPath, Resetting"
    logger "echo 0 > $sysPath/authorized"
    echo 0 > $sysPath/authorized
    logger "echo 1 > $sysPath/authorized"
    echo 1 > $sysPath/authorized
else
    logger "Could not find $ID"
fi


