#!/bin/sh
# Automaic run functions for the individual nodes

savedir=/home/pi
viddir="$savedir/Videos"
min_hd_space=$((1024*1024))	# 1 GB

echo "INFO: Node powered on"

free_space=`df --output=avail $savedir | tail -n1`
echo "INFO: Free space: $free_space ($((free_space/1024/1024)) GB)"

# If space back up nodes
if [ "$free_space" -lt "$min_hd_space" ]
then
    echo "ERROR: not enough space"
    # TODO: quit
else 
    echo "INFO: Saving videos to $viddir"
fi

ifaceup () {
    # Check if network interface is up
    file=/sys/class/net/$1/operstate
    
    if [ -f "$file" ]; then
	status=$(cat $file)
	# status is likely but not definitely "up"
    else
	status="down"
    fi
    
    echo "INFO: iface $1: $status"
    
    if [ ! "$status" = "down" ]; then
	return 0
    else
	return 1
    fi
}

test_connection () {
    ping -q -c 1 -W 1 raspberrypi.local > /dev/null
    # NOTE: kill SIGINT does not work during ping
    return $?
}

# Make sure usb interface is connected
ifaceup usb0
while ! test_connection
do
    echo "INFO: waiting for connection"
    sleep 10
done

echo "INFO: Array connection established"

# Check time syncing
ntp_server=$(timedatectl show-timesync | grep "ServerName" | sed 's/.*=//') 
if [ ! -z $ntp_server ]
then
    echo "INFO: Time synced to $ntp_server"
else
    # FIXME: does not work
    echo "WARNING: Time sync server down"
fi

fname=/home/pi/Videos/$(date -I'ns').h264
echo "INFO: recording video to $fname"
raspivid -o $fname -t 30000


echo "INFO: node-exec completed"

ifaceup wlan0; wlan0_up=$?
echo "DEBUG: wlan0: $wlan0_up";

# Check if user is logged in
# NOTE: should not matter
# if who | grep -q "pi"
# then
#     echo "INFO: pi is logged in: Staying up"
#     exit 0
# else
#     echo "INFO: pi is not logged in"
# fi

# Stay up if there is an outside connection

if [ $wlan0_up -eq 0 ]
then
    echo "INFO: Outside connection detected: Staying up"
    exit 0
else
    echo "INFO: No outside connection. Shutting down"
    #sudo shutdown now
fi

exit 0
